### PR TITLE
Use emitFile instead of outputFile

### PR DESCRIPTION
**Pull request by benmccann**
Closes https://github.com/thgh/rollup-plugin-css-only/issues/23

### CODE REVIEW

**Comment by thgh** [comment]
Awesome! No breaking change for users?

**Comment by benmccann** [comment]
I don't think there should be, but I didn't check that the output went to the same location, etc.

**Comment by thgh** [comment]
Hmm, it seems to write the files to /assets/[name]-[hash].css

**Comment by thgh** [comment]
Alright, fixed and released in v3 🎉

**Comment by benmccann** [comment]
thank you!!

**Pull request merged**
