### PR TITLE
Support Rollup v4

### PR DESCRIPTION
**Pull request by sockmaster27**
Tests seem to be passing, and I'm not seeing anything immediately relevant in the [release notes](https://github.com/rollup/rollup/releases).

### CODE REVIEW

**Comment by pioug** [comment]
I've published a fork in the meantime: https://www.npmjs.com/package/@pioug/rollup-plugin-css-only. It should be almost like a drop-in replacement.

```json
"rollup-plugin-css-only": "npm:@pioug/rollup-plugin-css-only@^5.0.0",
```

For reference, the equivalent changes for rollup-plugin-import-css (https://github.com/jleeson/rollup-plugin-import-css/pull/18) have been merged too.

@thgh, I can help maintain this plugin, at least by handling the chores, if you accept. I use it at work, so I don't mind spending time on it.

**Comment by thgh** [comment]
Hi @pioug what can I do to help you maintain this plugin?

I have invited you to the repo, feel free to resolve/merge where needed. Consider keeping changes small (or add tests).

Also consider if this plugin could be moved to the [@rollup/plugins](https://github.com/rollup/plugins) repo.

**Comment by thgh** [comment]
Published in v4.4

**Comment by pioug** [comment]
Thank you so much, @thgh, for the invitation 🙏

I think one thing that may be helpful too is having publishing rights on npm (my account: https://www.npmjs.com/~pioug) 💦 Like here, for example, I think the v4.4 is not published yet?

> Also, consider if this plugin could be moved to the [@rollup/plugins](https://github.com/rollup/plugins) repository.

That sounds even better and sustainable!

**Comment by thgh** [comment]
Oops, it errored, published for real now! https://www.npmjs.com/package/rollup-plugin-css-only

I'm ok transfering publishing rights, but security wise I would like to wait for a while and build some trust first. (most people volunteering to maintain and getting repo access end up not maintaining after all, so would rather limit the blast radius)

**Pull request merged**
